disabled_rules: # rule identifiers to exclude from running
  - nesting
  - trailing_whitespace
  - inclusive_language
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests
  - Playground
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: error # implicitly
force_try:
  severity: error # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 250
function_body_length:
  warning: 21
  error: 22
# they can set both implicitly with an array
type_body_length:
  warning: 200
  error: 201
# or they can set both explicitly
file_length:
  warning: 550
  error: 551
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 51
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    warning: 1 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)

